// Script para debuguear variables de entorno
console.log('=== DEBUG: Environment Variables ===');
console.log('NODE_ENV:', process.env.NODE_ENV);
console.log('');
console.log('=== DB_* variables ===');
console.log('DB_HOST:', process.env.DB_HOST);
console.log('DB_PORT:', process.env.DB_PORT);
console.log('DB_NAME:', process.env.DB_NAME);
console.log('DB_USER:', process.env.DB_USER);
console.log('DB_PASSWORD:', process.env.DB_PASSWORD ? '***' : 'undefined');
console.log('');
console.log('=== PG* variables ===');
console.log('PGHOST:', process.env.PGHOST);
console.log('PGPORT:', process.env.PGPORT);
console.log('PGDATABASE:', process.env.PGDATABASE);
console.log('PGUSER:', process.env.PGUSER);
console.log('PGPASSWORD:', process.env.PGPASSWORD ? '***' : 'undefined');
console.log('');
console.log('=== DATABASE_URL variables ===');
console.log('DATABASE_URL:', process.env.DATABASE_URL ? '***' : 'undefined');
console.log('');
console.log('=== Parsed config ===');
const envs = require('./src/config/envs');
console.log('DB_HOST:', envs.DB_HOST);
console.log('DB_PORT:', envs.DB_PORT);
console.log('DB_NAME:', envs.DB_NAME);
console.log('DB_USER:', envs.DB_USER);
console.log('DB_PASSWORD:', envs.DB_PASSWORD ? '***' : 'undefined');
console.log('DB_SSL:', envs.DB_SSL);
console.log('DATABASE_URL:', envs.DATABASE_URL ? '***' : 'undefined');
